# Generated by Django 5.1.4 on 2025-01-08 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('mileage', models.IntegerField()),
                ('vehicle_age', models.IntegerField()),
                ('reported_issues', models.IntegerField(default=0)),
                ('fuel_efficiency', models.DecimalField(decimal_places=15, max_digits=17)),
                ('service_history', models.IntegerField()),
                ('accident_history', models.IntegerField(default=0)),
                ('tire_condition', models.IntegerField()),
                ('brake_condition', models.IntegerField()),
                ('battery_status', models.IntegerField()),
                ('days_since_last_service', models.IntegerField(default=0)),
                ('days_to_warranty_expire', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.TextField()),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=1, max_digits=5)),
                ('date', models.DateField()),
                ('rating', models.PositiveIntegerField()),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.car')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.driver')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
            },
        ),
    ]
