# Generated by Django 5.1.4 on 2025-01-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='accident_history',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='days_since_last_service',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='reported_issues',
            field=models.IntegerField(),
        ),
    ]
